# These are supported funding model platforms

patreon: # Replace with a single Patreon username
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
custom: ['https://www.youtube.com/channel/UCVOQobByo_2WISQf2037eXQ', '']
