name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks you for starting an issue! We will get back to you shortly. Please wait.'
        pr-message: 'Thanks you for starting a pull request. We will get back to you shortly. Please wait.'
